baseurl = "http://localhost://57385" # Hostname (and path) to the root.
title = "Zoe's website" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Zoe González García" # Author's name.
    info = "Portal a los escaparates 'littles notes' y 'blogueando'" # Author's job title or info.
    description = "Zoe's website es un escaparate de distintos tipos de contenido, mayormente enfocados a la programación web" # Site description.
    # keywords = "blog,hugo,php"  Site keywords.
    avatarurl = "images/avatar_w_z.png" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "Este sitio está en construcción. Si ves algo que no te gusta me gustaría que me lo comunicaras" # Add footer content
    fixedbarContent = "¿Qúe quieres saber?→" # Add fixedbar content
    fixedbarContentAfter = "Gracias! Si algo que ves te gusta compártelo." # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = true  # new add
    enableFacebookShare = true # new add
    enableHatenaShare = true   # new add
    enableLineShare = true     # new add
    enableLinkedInShare = true # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "English|Spanish" # Separates menus from language selectors when site is multilingual.
    

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/naro143/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/naro143/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/naro143/"
[[params.social]]
    # If icon is not set, Text is displayed.
    name = "LinkedIn"
    weight = 4
    url = "https://www.linkedin.com/in/naro143/"

# Menu links
[[menu.main]]
    name = "Little notes"
    weight = 1
    url  = "/Users/zoeGonGar/zoe_website/content/little_notes"
[[menu.main]]
    name = "blogueando"
    weight = 2
    url = "/content/patatas/12.md"

